---
- hosts: zabbix_agents
  gather_facts: yes
  tasks:

      - name: Download zabbix repo package for Ubuntu\Debian
        get_url:
          url: http://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1%2Bubuntu20.04_all.deb
          dest: /tmp/zabbix.deb
        when: ansible_os_family == "Debian"

      - name: Install zabbix repo for Ubuntu\Debian
        become: yes
        apt:
          deb: /tmp/zabbix.deb
          state: present
        when: ansible_os_family == "Debian"

      - name: Install zabbix repo for RHEL\Centos
        become: yes
        yum:
         name: http://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-agent-5.4.9-1.el7.x86_64.rpm
         state: present
        when: ansible_os_family == "RedHat"

      - name: Install zabbix agent for Ubuntu\Debian
        become: yes
        apt:
          name: zabbix-agent
          state: present
          update_cache: yes
        when: ansible_os_family == "Debian"

      - name: Install zabbix agent for RHEL\Centos
        become: yes
        yum:
          name: zabbix-agent
          state: present
        when: ansible_os_family == "RedHat"

      - name: Stop service zabbix-agent
        become: yes
        service:
          name: zabbix-agent
          state: stopped

      - name: Remove zabbix config file
        become: yes
        file:
          path: /etc/zabbix/zabbix_agentd.conf
          state: absent

      - name: Create new zabbix config file from template
        become: yes
        template:
          src: "templates/zabbix_agentd.conf.j2"
          dest: "/etc/zabbix/zabbix_agentd.conf"

      - name: Start service zabbix-agent
        become: yes
        service:
          name: zabbix-agent
          state: started
          enabled: yes
